export const environment = {
  production: true,
  entorno: "test",
  autenticacion: true,
  notificaciones: false,
  menuApps: false,
  appname: "sga",
  appMenu: "SGA_MF",
  TOKEN: {
    AUTORIZATION_URL: "https://autenticacion.portaloas.udistrital.edu.co/oauth2/authorize",
    CLIENTE_ID: "Mg40MfT62GA_vcPMIJurpX3pzx4a",
    RESPONSE_TYPE: "id_token token",
    SCOPE: "openid email role documento",
    REDIRECT_URL: "https://sgamicroclientes.portaloas.udistrital.edu.co",
    SIGN_OUT_URL: "https://autenticacion.portaloas.udistrital.edu.co/oidc/logout",
    SIGN_OUT_REDIRECT_URL: "https://sgamicroclientes.portaloas.udistrital.edu.co",
    AUTENTICACION_MID: "https://autenticacion.portaloas.udistrital.edu.co/apioas/autenticacion_mid/v1/token/userRol",
  },
  parcels: {
    "@udistrital/root-config": "https://sgamicroclientes.portaloas.udistrital.edu.co/udistrital-root-config.js",
    "@udistrital/core-mf": "https://coreclientes.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-datos-mf": "https://sgadatos.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-administracion-mf": "https://sgaadministracion.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-espacios-academicos-mf": "https://sgaespaciosacademicos.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-gestionar-periodo-mf": "https://sgagestionperiodo.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-derechos-pecuniarios-mf": "https://sgaderechospecuniarios.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-notas-mf":"https://sganotas.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-gestion-horarios-mf":"https://sgagestionhorario.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-plan-estudios-mf": "https://sgaplanestudios.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-admisiones-mf": "https://sgaadmisiones.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-calendarioacademico-mf": "https://sgacalendarioacademico.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-practicas-academicas-mf": "https://sgapracticasacademicas.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-inscripcion-mf": "https://sgainscripcion.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-proyecto-curricular-mf": "https://sgaproyectocurricular.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-tirilla-noticias-mf":"",
    "@udistrital/sga-plan-docente-mf":"https://sgaplandocente.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-preinscripciones-mf":"",
    "@udistrital/sga-evaluacion-docente-mf":"//localhost:4218/main.js",
    "@udistrital/formularios-dinamicos-mf":"https://formulariosdinamicos.portaloas.udistrital.edu.co/main.js"

  }
};  
