export const environment = {
  production: false,
  entorno: "test",
  autenticacion: true,
  notificaciones: false,
  menuApps: false,
  appname: "sga",
  appMenu: "SGA",
  TOKEN: {
    AUTORIZATION_URL: "https://autenticacion.portaloas.udistrital.edu.co/oauth2/authorize",
    CLIENTE_ID: "1OaC8gIVEfG8WxjrB37saszNQ5ga",
    RESPONSE_TYPE: "id_token token",
    SCOPE: "openid email role documento",
    REDIRECT_URL: "https://pruebassgamicroclientes.portaloas.udistrital.edu.co",
    SIGN_OUT_URL: "https://autenticacion.portaloas.udistrital.edu.co/oidc/logout",
    SIGN_OUT_REDIRECT_URL: "https://pruebassgamicroclientes.portaloas.udistrital.edu.co",
    AUTENTICACION_MID: "https://autenticacion.portaloas.udistrital.edu.co/apioas/autenticacion_mid/v1/token/userRol",
  },
  parcels: {
    "@udistrital/root-config": "https://pruebassgamicroclientes.portaloas.udistrital.edu.co/udistrital-root-config.js",
    "@udistrital/core-mf": "https://pruebascoreclientes.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-datos-mf": "https://pruebassgadatos.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-administracion-mf": "https://pruebassgaadministracion.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-espacios-academicos-mf": "https://pruebassgaespaciosacademicos.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-gestionar-periodo-mf": "https://pruebassgagestionperiodo.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-derechos-pecuniarios-mf": "https://pruebassgaderechospecuniarios.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-notas-mf":"https://pruebassganotas.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-gestion-horarios-mf":"https://pruebassgagestionhorario.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-plan-estudios-mf": "https://pruebassgaplanestudios.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-admisiones-mf": "https://pruebassgaadmisiones.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-calendarioacademico-mf": "https://pruebassgacalendarioacademico.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-practicas-academicas-mf": "https://pruebassgapracticasacademicas.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-inscripcion-mf": "https://pruebassgainscripcion.portaloas.udistrital.edu.co/main.js",
    "@udistrital/sga-proyecto-curricular-mf": "https://pruebassgaproyectocurricular.portaloas.udistrital.edu.co/main.js",
  }
};
